# Basic
title: Lanmaq's Blog
subtitle: The body is cleaner than the soul！
# welcome_message: <a href="https://github.com/Lanmaq" target="_blank">Write Code</a>
description: An iOS rookie, just taking off.
# creator: <a href="http://lanmaq.com">@Lanmaq</a>

url: "http://lanmaq.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Life, description: Link life, url: 'http://www.lanmaq.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: Lanmaq
    github: Lanmaq
    instagram: Lanmaq
    # twitter: Lanmaq
    # gplus: 0
    mail: lanmaqmay66@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
